prefix aama:	 <http://id.oi.uchicago.edu/aama/2013/>
prefix aamas:	 <http://id.oi.uchicago.edu/aama/2013/schema/>
prefix rdf:	 <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:	 <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?language ?property ?value
WHERE {
GRAPH <http://oi.uchicago.edu/aama/2013/graph/oromo> {
	  ?pred aamas:lang ?lang .
	  ?lang rdfs:label ?language .
      ?pred rdfs:label ?value .
      ?pred rdf:type ?type .
      BIND (SUBSTR(str(?type), 37) AS ?property)
	  FILTER ( regex(?property, "Lexeme"))
}}
ORDER BY ASC(?property) ASC(?value)
