# Output not that different from class.template. Cf. LS ex449.rq
# Basically the same as propertiesUsed.rq. Cf. LS ex534.ra

prefix aama:	 <http://id.oi.uchicago.edu/aama/2013/>
prefix aamas:	 <http://id.oi.uchicago.edu/aama/2013/schema/>
prefix rdf:	 <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:	 <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?property
WHERE {
GRAPH <http://oi.uchicago.edu/aama/2013/graph/afar> {
		?s ?property ?o . 
	}
}
ORDER BY ?property
# LIMIT 50

