# filename: ex451.rq

PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX owl: <http://www.w3.org/2002/07/owl#> 

SELECT DISTINCT ?class
WHERE {
#?s owl:equivalentProperty ?o ;
?s gr:hasNext ?o ;
   a ?class . 
}

