# filename: ex465.rq

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX orm:   <http://id.oi.uchicago.edu/aama/2013/oromo/>

SELECT ?property ?domain
WHERE
{ ?property rdfs:Domain ?domain }

