PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama:	 <http://id.oi.uchicago.edu/aama/2013/>
PREFIX aamas:	 <http://id.oi.uchicago.edu/aama/2013/schema/>
PREFIX aamag:	 <http://oi.uchicago.edu/aama/2013/graph/>
PREFIX orm:   <http://id.oi.uchicago.edu/aama/2013/oromo/>
PREFIX Orm:   <http://id.oi.uchicago.edu/aama/2013/Oromo/>

SELECT ?g ?dervStem  ?num ?pers ?gen ?token
WHERE
{
	GRAPH aamag:oromo
	{
		?s	orm:pos	Orm:Verb . 
		?s	aama:lang	aama:Oromo .
		?s	orm:clauseType	Orm:Main . 
		?s	orm:polarity	Orm:Affirmative . 
		?s	orm:tam	Orm:Present . 
		OPTIONAL { ?s	orm:derivedStem	?QdervStem . 
			?QdervStem	rdfs:label	?dervStem . }
		?s	orm:number	?number . 
		?number	rdfs:label	?num . 
		?s	orm:person	?person . 
		?person	rdfs:label	?pers . 
		?s	orm:gender	?gender . 
		?gender	rdfs:label	?gen . 
		?s	orm:token	?token . 
	}
}
ORDER BY ?dervStem   DESC(?num) ?pers DESC(?gen)

SELECT ?derivedStem ?tam  ?num ?pers ?gen ?token
WHERE
{
	GRAPH aamag:oromo
	{
		?s	orm:pos	Orm:Verb . 
		?s	aama:lang	aama:Oromo .
		?s	orm:clauseType	Orm:Main . 
		?s	orm:polarity	Orm:Affirmative . 
		?s	orm:tem	Orm:Present . 
		OPTIONAL { ?s	orm:derivedStem	?QderivedStem . 
 		?QderivedStem	rdfs:label	?derivedStem . }
		OPTIONAL { ?s	orm:tam	?Qtam . 
 		?Qtam	rdfs:label	?tam . }
		OPTIONAL { ?s	orm:number	?number . 
		?number	rdfs:label	?num . }
		?s	orm:person	?person . 
		?person	rdfs:label	?pers . 
		OPTIONAL { ?s	orm:gender	?gender . 
		?gender	rdfs:label	?gen . }
		?s	orm:token	?token . 
	}
}
ORDER BY ?derivedStem ?tam   DESC(?num) ?pers DESC(?gen)

