# = LS ex538.rq. Offers no advantages over propertiesUsed.template,
#  and affords less control over number of graphs to be returned 
# (one, several specified, all)

SELECT DISTINCT ?graph ?property
WHERE 
{ 
  #{ ?s ?property ?o . }
  #UNION
	#{ 
		GRAPH ?graph { ?s ?property ?o } 
	#}  
}
ORDER BY ?graph DESC(?property)
LIMIT 50
