PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?language { ?s aama:lang ?lang . ?lang rdfs:label ?language . } ORDER BY ?language