# output-lang-prop-val.rq
# what prop+val combinations occur, by language

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama:	 <http://id.oi.uchicago.edu/aama/2013/>

SELECT DISTINCT ?lang  ?property ?value 
WHERE 
{
   ?s ?p ?o .
   ?s aama:lang ?language .
   ?language rdfs:label ?lang .
   ?p rdfs:label ?property .
   ?o rdfs:label ?value
}
ORDER BY ?lang  ?property ?value 
