# output-prop-val-lang.rq
# list of each prop and its values in each language

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>

SELECT DISTINCT ?property ?value ?lang ?langVar
WHERE 
{
   ?s ?p ?o .
   ?s aama:lang ?language .
   ?language rdfs:label ?lang .
   OPTIONAL { ?s aama:langVar ?languageVar .
						?languageVar rdfs:label ?langVar . }
   ?p rdfs:label ?property .
   ?o rdfs:label ?value .
   FILTER(!(?p IN (aama:pos, aama:person, aama:gender, aama:number))) .
 	FILTER(!(?value IN ("⊥", "⊤", "x22a4", "", "U"))) .

   }
ORDER BY ?property ?value ?lang ?langVar

