#output-pdgmlex.rq (-- to be saved as LANG(-LANGVAR)-pdgm-lex.tsv)
# This will return all the lexid (lexeme IDs), and properties
#  in the archive (relies on fact that ?lexid is only ID with object aama:lexid
# (substitute archive language and variety name for <LANG> and <LANGVAR>)
# This query is used both for datastore2n3 and datastore2documentationIndex
# operations.

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>

SELECT DISTINCT ?qlexid ?qp ?qo
WHERE
{
	?lexid ?p ?o ;
	?x aama:lexid ;
	aama:lang aama:LANG	;
	#aama:langVar aama:LANGVAR ; 
	BIND (CONCAT("aama:", SUBSTR(str(?lexid), 41)) AS ?qlexid)
	BIND (IF(regex(str(?p), "www.w3"),
			  "a",
			  CONCAT("aama:", SUBSTR(str(?p), 41))
				) AS ?qp )
	BIND (IF(regex(str(?o), "oi.uchicago"),
			  CONCAT("aama:", SUBSTR(str(?o), 41)),
			  ?o
				) AS ?qo )
}
ORDER BY ?qlexid ?qp

