# output-lang-prop-val.rq
# what prop occur, by language

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>

SELECT DISTINCT ?lang ?langVar ?property 
WHERE 
{
   ?s ?p ?o .
   ?s aama:lang ?language .
   ?s aama:lang aama:somali .
   ?language rdfs:label ?lang .
   ?s aama:langVar ?languageVar .
	?languageVar rdfs:label ?langVar .
   ?p rdfs:label ?property .
    # FILTER(!(?p IN (aama:pos, aama:person, aama:gender, aama:number))) .
 
}
ORDER BY ?lang ?langVar ?property 


# lang-props.rq
# list of each prop and its values in each language

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>

SELECT DISTINCT ?language ?property  
WHERE 
{
   ?s ?p ?o .
   ?s aama:lang aama:somali .
   ?p rdfs:label ?property .
   }
ORDER BY  ?language ?property  
