PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>
SELECT  ?polarity ?clause ?num ?pers ?gen ?token
WHERE
{
   ?s aama:tam aama:present .
   OPTIONAL { ?s aama:clauseType ?clauseType .
       ?clauseType rdfs:label ?clause . }
   ?s aama:polarity ?pol .
   ?pol rdfs:label ?polarity .
   ?s aama:dervStem aama:base .
   ?s aama:lang aama:oromo .
   ?s aama:number ?number .
   ?number rdfs:label ?num .
 ?s aama:person ?person .
 ?person rdfs:label ?pers .
 ?s aama:gender ?gender .
 ?gender rdfs:label ?gen .
 ?s aama:token ?token .
}
ORDER BY ?polarity ?clause DESC(?num) ?pers DESC(?gen)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>
SELECT  ?language ?tense ?polarity ?lexlabel ?num ?pers ?gen ?token
WHERE
{
   ?s aama:lang ?lang .
   ?lang rdfs:label ?language .
   ?s aama:tam ?tam .
   ?tam rdfs:label ?tense .
   ?s aama:polarity ?pol .
   ?pol rdfs:label ?polarity .
	?s aama:lexlabel ?lexlabel .
   ?s aama:number ?number .
   ?number rdfs:label ?num .
 ?s aama:person ?person .
 ?person rdfs:label ?pers .
 ?s aama:gender ?gender .
 ?gender rdfs:label ?gen .
 ?s aama:token ?token .
}
ORDER BY ?language ?tense ?polarity ?lexlabel DESC(?num) ?pers DESC(?gen)
