# Print out specific paradigm:
# display-pdgm-by-label.rq

#This gets you raw paradigm
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>

SELECT ?p ?v
WHERE 
{
   ?pdgmID aama:pdgmlabel "somali-PPoss".
   ?s aama:pid ?pdgmID .
   ?s ?p ?v .
}
ORDER BY ?s ?p ?v

#This yields only property-value combos
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>

SELECT ?predicate ?value
WHERE 
{
   ?pdgmID aama:pdgmlabel "bayso-NNum".
   ?s aama:pid ?pdgmID .
   ?s ?p ?v .
   ?p rdfs:label ?predicate .
   ?v rdfs:label ?value .
}
ORDER BY ?predicate ?value


# to get paradigm:

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>
SELECT DISTINCT  ?pdgmLabel ?p ?o
WHERE
{
   ?s ?p ?o .
   ?s aama:pid ?pid .
   ?pid aama:pdgmlabel ?pdgmLabel . 
   ?s aama:lang aama:beja .
   ?s aama:langVar aama:hadendowa .
   { ?s aama:genitive ?o . }
   UNION
   { ?s aama:genPoss ?o .}
}
ORDER BY ?pdgmLabel ?p ?o

