PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>

SELECT ?dervStem  ?num ?pers ?gen ?token
WHERE
{
	?s	aama:pos	aama:verb . 
	?s	aama:lang	aama:oromo .
	?s	aama:clauseType	aama:main . 
	?s	aama:polarity	aama:affirmative . 
	?s	aama:tam	aama:present . 
	OPTIONAL { ?s	aama:dervStem	?QdervStem . 
 		?QdervStem	rdfs:label	?dervStem . }
	?s	aama:number	?number . 
	?number	rdfs:label	?num . 
	?s	aama:person	?person . 
	?person	rdfs:label	?pers . 
	?s	aama:gender	?gender . 
	?gender	rdfs:label	?gen . 
	?s	aama:token	?token . 
}
ORDER BY ?dervStem   DESC(?num) ?pers DESC(?gen)
