#output-pdgms-rdfs.rq (-- to be saved as LANG(-LANGVAR)-pdgm-rdfs.tsv)
# This will return all the rdfs:label values which occur in the datastore for 
# a given language.
# (substitute archive language and variety name for <LANG> and <LANGVAR>)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>

SELECT DISTINCT ?qterm ?qpred ?label
WHERE
{
	{?s ?term ?o .}
	UNION 
	{?s ?p ?term .}
	?term ?pred ?label .
	?term rdfs:label ?label .
	?s aama:lang aama:<LANG> .
	OPTIONAL  { ?s aama:langVar aama:<LANGVAR> . }
	BIND (CONCAT("aama:", SUBSTR(str(?term), 41)) AS ?qterm)
	BIND (CONCAT("rdfs:", SUBSTR(str(?pred), 38)) AS ?qpred)
}
ORDER BY ?qterm ?label