----------------------------------------------------
| pdgmlabel                         | prop1        |
====================================================
| "oromo-VBaseNegImprtvSmpl-beek"   | "dervStem"   |
| "oromo-VBaseNegImprtvSmpl-beek"   | "polarity"   |
| "oromo-VBaseNegImprtvSmpl-beek"   | "tam"        |
| "oromo-VBaseSubAffPresSmpl-beek"  | "clauseType" |
| "oromo-VBaseSubAffPresSmpl-beek"  | "dervStem"   |
| "oromo-VBaseSubAffPresSmpl-beek"  | "polarity"   |
| "oromo-VBaseSubAffPresSmpl-beek"  | "tam"        |
| "oromo-VCausMainAffPresSmpl-beek" | "clauseType" |
| "oromo-VCausMainAffPresSmpl-beek" | "dervStem"   |
| "oromo-VCausMainAffPresSmpl-beek" | "polarity"   |
| "oromo-VCausMainAffPresSmpl-beek" | "tam"        |
| "oromo-VPassSubAffPresSmpl-beek"  | "clauseType" |
| "oromo-VPassSubAffPresSmpl-beek"  | "dervStem"   |
| "oromo-VPassSubAffPresSmpl-beek"  | "polarity"   |
| "oromo-VPassSubAffPresSmpl-beek"  | "tam"        |
| "oromo-VBaseAffImprtvSmpl-beek"   | "dervStem"   |
| "oromo-VBaseAffImprtvSmpl-beek"   | "polarity"   |
| "oromo-VBaseAffImprtvSmpl-beek"   | "tam"        |
| "oromo-VPassAffImprtvSmpl-beek"   | "dervStem"   |
| "oromo-VPassAffImprtvSmpl-beek"   | "polarity"   |
| "oromo-VPassAffImprtvSmpl-beek"   | "tam"        |
| "oromo-VCausMainNegPresSmpl-beek" | "clauseType" |
| "oromo-VCausMainNegPresSmpl-beek" | "dervStem"   |
| "oromo-VCausMainNegPresSmpl-beek" | "polarity"   |
| "oromo-VCausMainNegPresSmpl-beek" | "tam"        |
| "oromo-VPassMainAffPresSmpl-beek" | "clauseType" |
| "oromo-VPassMainAffPresSmpl-beek" | "dervStem"   |
| "oromo-VPassMainAffPresSmpl-beek" | "polarity"   |
| "oromo-VPassMainAffPresSmpl-beek" | "tam"        |
| "oromo-VPassSubNegPresSmpl-beek"  | "clauseType" |
| "oromo-VPassSubNegPresSmpl-beek"  | "dervStem"   |
| "oromo-VPassSubNegPresSmpl-beek"  | "polarity"   |
| "oromo-VPassSubNegPresSmpl-beek"  | "tam"        |
| "oromo-VBaseSubNegPresSmpl-beek"  | "clauseType" |
| "oromo-VBaseSubNegPresSmpl-beek"  | "dervStem"   |
| "oromo-VBaseSubNegPresSmpl-beek"  | "polarity"   |
| "oromo-VBaseSubNegPresSmpl-beek"  | "tam"        |
| "oromo-VPassMainNegPresSmpl-beek" | "clauseType" |
| "oromo-VPassMainNegPresSmpl-beek" | "dervStem"   |
| "oromo-VPassMainNegPresSmpl-beek" | "polarity"   |
| "oromo-VPassMainNegPresSmpl-beek" | "tam"        |
| "oromo-VCausSubAffPresSmpl-beek"  | "clauseType" |
| "oromo-VCausSubAffPresSmpl-beek"  | "dervStem"   |
| "oromo-VCausSubAffPresSmpl-beek"  | "polarity"   |
| "oromo-VCausSubAffPresSmpl-beek"  | "tam"        |
| "oromo-VBaseAffPastSmpl-beek"     | "dervStem"   |
| "oromo-VBaseAffPastSmpl-beek"     | "polarity"   |
| "oromo-VBaseAffPastSmpl-beek"     | "tam"        |
| "oromo-VBaseMainAffPresSmpl-beek" | "clauseType" |
| "oromo-VBaseMainAffPresSmpl-beek" | "dervStem"   |
| "oromo-VBaseMainAffPresSmpl-beek" | "polarity"   |
| "oromo-VBaseMainAffPresSmpl-beek" | "tam"        |
| "oromo-VBaseNegPastSmpl-beek"     | "dervStem"   |
| "oromo-VBaseNegPastSmpl-beek"     | "polarity"   |
| "oromo-VBaseNegPastSmpl-beek"     | "tam"        |
| "oromo-VMidAffPastSmpl-beek"      | "dervStem"   |
| "oromo-VMidAffPastSmpl-beek"      | "polarity"   |
| "oromo-VMidAffPastSmpl-beek"      | "tam"        |
| "oromo-VCausAffPastSmpl-beek"     | "dervStem"   |
| "oromo-VCausAffPastSmpl-beek"     | "polarity"   |
| "oromo-VCausAffPastSmpl-beek"     | "tam"        |
| "oromo-VCausAffImprtvSmpl-beek"   | "dervStem"   |
| "oromo-VCausAffImprtvSmpl-beek"   | "polarity"   |
| "oromo-VCausAffImprtvSmpl-beek"   | "tam"        |
| "oromo-VMidSubNegPresSmpl-beek"   | "clauseType" |
| "oromo-VMidSubNegPresSmpl-beek"   | "dervStem"   |
| "oromo-VMidSubNegPresSmpl-beek"   | "polarity"   |
| "oromo-VMidSubNegPresSmpl-beek"   | "tam"        |
| "oromo-VMidNegImprtvSmpl-beek"    | "dervStem"   |
| "oromo-VMidNegImprtvSmpl-beek"    | "polarity"   |
| "oromo-VMidNegImprtvSmpl-beek"    | "tam"        |
| "oromo-VMidAffImprtvSmpl-beek"    | "dervStem"   |
| "oromo-VMidAffImprtvSmpl-beek"    | "polarity"   |
| "oromo-VMidAffImprtvSmpl-beek"    | "tam"        |
| "oromo-VBaseMainNegPresSmpl-beek" | "clauseType" |
| "oromo-VBaseMainNegPresSmpl-beek" | "dervStem"   |
| "oromo-VBaseMainNegPresSmpl-beek" | "polarity"   |
| "oromo-VBaseMainNegPresSmpl-beek" | "tam"        |
| "oromo-VCausSubNegPresSmpl-beek"  | "clauseType" |
| "oromo-VCausSubNegPresSmpl-beek"  | "dervStem"   |
| "oromo-VCausSubNegPresSmpl-beek"  | "polarity"   |
| "oromo-VCausSubNegPresSmpl-beek"  | "tam"        |
| "oromo-VMidSubAffPresSmpl-beek"   | "clauseType" |
| "oromo-VMidSubAffPresSmpl-beek"   | "dervStem"   |
| "oromo-VMidSubAffPresSmpl-beek"   | "polarity"   |
| "oromo-VMidSubAffPresSmpl-beek"   | "tam"        |
| "oromo-VCausNegPastSmpl-beek"     | "dervStem"   |
| "oromo-VCausNegPastSmpl-beek"     | "polarity"   |
| "oromo-VCausNegPastSmpl-beek"     | "tam"        |
| "oromo-VCompoundTense"            | "polarity"   |
| "oromo-VCompoundTense"            | "tam"        |
| "oromo-VCompoundTense"            | "tokenType"  |
| "oromo-VMidMainNegPresSmpl-beek"  | "clauseType" |
| "oromo-VMidMainNegPresSmpl-beek"  | "dervStem"   |
| "oromo-VMidMainNegPresSmpl-beek"  | "polarity"   |
| "oromo-VMidMainNegPresSmpl-beek"  | "tam"        |
| "oromo-VMidNegPastSmpl-beek"      | "dervStem"   |
| "oromo-VMidNegPastSmpl-beek"      | "polarity"   |
| "oromo-VMidNegPastSmpl-beek"      | "tam"        |
| "oromo-VPassNegImprtvSmpl-beek"   | "dervStem"   |
| "oromo-VPassNegImprtvSmpl-beek"   | "polarity"   |
| "oromo-VPassNegImprtvSmpl-beek"   | "tam"        |
| "oromo-VMidMainAffPresSmpl-beek"  | "clauseType" |
| "oromo-VMidMainAffPresSmpl-beek"  | "dervStem"   |
| "oromo-VMidMainAffPresSmpl-beek"  | "polarity"   |
| "oromo-VMidMainAffPresSmpl-beek"  | "tam"        |
| "oromo-VCausNegImprtvSmpl-beek"   | "dervStem"   |
| "oromo-VCausNegImprtvSmpl-beek"   | "polarity"   |
| "oromo-VCausNegImprtvSmpl-beek"   | "tam"        |
| "oromo-VPassNegPastSmpl-beek"     | "dervStem"   |
| "oromo-VPassNegPastSmpl-beek"     | "polarity"   |
| "oromo-VPassNegPastSmpl-beek"     | "tam"        |
| "oromo-VJuss-beek"                | "dervStem"   |
| "oromo-VJuss-beek"                | "polarity"   |
| "oromo-VJuss-beek"                | "tam"        |
| "oromo-VPassAffPastSmpl-beek"     | "dervStem"   |
| "oromo-VPassAffPastSmpl-beek"     | "polarity"   |
| "oromo-VPassAffPastSmpl-beek"     | "tam"        |
----------------------------------------------------
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>

SELECT DISTINCT ?pdgmlabel ?prop1 # ?val1 
WHERE 
{
    ?pid ?term aama:pid ;
	aama:pdgmlabel ?pdgmlabel .
	?s ?p ?o ;
    aama:pid ?pid ;
    aama:tam  ?tam ;
	aama:person ?person ;
	aama:lang aama:oromo .
   ?p rdfs:label ?prop1 .
   ?o rdfs:label ?val1  .
  	FILTER (?p NOT IN ( aama:lang, aama:langVar, aama:gender, aama:number, aama:person, aama:pos, rdf:type))
  	FILTER (?o NOT IN ( aama:Term))
 
}
ORDER BY ?pid ?prop1
