----------------
| prop1        |
================
| "clauseType" |
| "dervStem"   |
| "polarity"   |
| "tam"        |
| "tokenType"  |
----------------
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>

SELECT DISTINCT  ?prop1
WHERE 
{
	?s ?p ?o ;
    aama:tam  ?tam ;
	aama:person ?person ;
	aama:lang aama:oromo .
   ?p rdfs:label ?prop1 .
   ?o rdfs:label ?val1  .
  	FILTER (?p NOT IN ( aama:lang, aama:langVar, aama:gender, aama:number, aama:person, aama:pos, rdf:type))
 
}
ORDER BY  ?prop1
