-------------------------------------------------------------------------------
| pdgmlabel                         | prop1         | val1                    |
===============================================================================
| "oromo-VBaseNegImprtvSmpl-beek"   | "dervStem"    | "base"                  |
| "oromo-VBaseNegImprtvSmpl-beek"   | "polarity"    | "negative"              |
| "oromo-VBaseNegImprtvSmpl-beek"   | "tam"         | "imperative"            |
| "oromo-VBaseSubAffPresSmpl-beek"  | "clauseType"  | "subordinate"           |
| "oromo-VBaseSubAffPresSmpl-beek"  | "dervStem"    | "base"                  |
| "oromo-VBaseSubAffPresSmpl-beek"  | "polarity"    | "affirmative"           |
| "oromo-VBaseSubAffPresSmpl-beek"  | "tam"         | "present"               |
| "oromo-VCausMainAffPresSmpl-beek" | "clauseType"  | "main"                  |
| "oromo-VCausMainAffPresSmpl-beek" | "dervStem"    | "S"                     |
| "oromo-VCausMainAffPresSmpl-beek" | "polarity"    | "affirmative"           |
| "oromo-VCausMainAffPresSmpl-beek" | "tam"         | "present"               |
| "oromo-VPassSubAffPresSmpl-beek"  | "clauseType"  | "subordinate"           |
| "oromo-VPassSubAffPresSmpl-beek"  | "dervStem"    | "M"                     |
| "oromo-VPassSubAffPresSmpl-beek"  | "polarity"    | "affirmative"           |
| "oromo-VPassSubAffPresSmpl-beek"  | "tam"         | "present"               |
| "oromo-VBaseAffImprtvSmpl-beek"   | "dervStem"    | "base"                  |
| "oromo-VBaseAffImprtvSmpl-beek"   | "polarity"    | "affirmative"           |
| "oromo-VBaseAffImprtvSmpl-beek"   | "tam"         | "imperative"            |
| "oromo-VPassAffImprtvSmpl-beek"   | "dervStem"    | "M"                     |
| "oromo-VPassAffImprtvSmpl-beek"   | "polarity"    | "affirmative"           |
| "oromo-VPassAffImprtvSmpl-beek"   | "tam"         | "imperative"            |
| "oromo-VCausMainNegPresSmpl-beek" | "clauseType"  | "main"                  |
| "oromo-VCausMainNegPresSmpl-beek" | "dervStem"    | "S"                     |
| "oromo-VCausMainNegPresSmpl-beek" | "polarity"    | "negative"              |
| "oromo-VCausMainNegPresSmpl-beek" | "tam"         | "present"               |
| "oromo-VPassMainAffPresSmpl-beek" | "clauseType"  | "main"                  |
| "oromo-VPassMainAffPresSmpl-beek" | "dervStem"    | "M"                     |
| "oromo-VPassMainAffPresSmpl-beek" | "polarity"    | "affirmative"           |
| "oromo-VPassMainAffPresSmpl-beek" | "tam"         | "present"               |
| "oromo-VPassSubNegPresSmpl-beek"  | "clauseType"  | "subordinate"           |
| "oromo-VPassSubNegPresSmpl-beek"  | "dervStem"    | "M"                     |
| "oromo-VPassSubNegPresSmpl-beek"  | "polarity"    | "negative"              |
| "oromo-VPassSubNegPresSmpl-beek"  | "tam"         | "present"               |
| "oromo-VBaseSubNegPresSmpl-beek"  | "clauseType"  | "subordinate"           |
| "oromo-VBaseSubNegPresSmpl-beek"  | "dervStem"    | "base"                  |
| "oromo-VBaseSubNegPresSmpl-beek"  | "polarity"    | "negative"              |
| "oromo-VBaseSubNegPresSmpl-beek"  | "tam"         | "present"               |
| "oromo-VPassMainNegPresSmpl-beek" | "clauseType"  | "main"                  |
| "oromo-VPassMainNegPresSmpl-beek" | "dervStem"    | "M"                     |
| "oromo-VPassMainNegPresSmpl-beek" | "polarity"    | "negative"              |
| "oromo-VPassMainNegPresSmpl-beek" | "tam"         | "present"               |
| "oromo-VCausSubAffPresSmpl-beek"  | "clauseType"  | "subordinate"           |
| "oromo-VCausSubAffPresSmpl-beek"  | "dervStem"    | "S"                     |
| "oromo-VCausSubAffPresSmpl-beek"  | "polarity"    | "affirmative"           |
| "oromo-VCausSubAffPresSmpl-beek"  | "tam"         | "present"               |
| "oromo-VCop-have"                 | "copType"     | "existence"             |
| "oromo-VCop-have"                 | "copType"     | "occurrence"            |
| "oromo-VCop-have"                 | "copType"     | "predication"           |
| "oromo-VCop-have"                 | "pdgmSubType" | "copula"                |
| "oromo-VCop-have"                 | "polarity"    | "affirmative"           |
| "oromo-VCop-have"                 | "polarity"    | "negative"              |
| "oromo-VCop-have"                 | "polarity"    | "?"                     |
| "oromo-VCop-have"                 | "tam"         | "nonPast-nonPres"       |
| "oromo-VCop-have"                 | "tam"         | "past"                  |
| "oromo-VCop-have"                 | "tam"         | "present"               |
| "oromo-VBaseAffPastSmpl-beek"     | "dervStem"    | "base"                  |
| "oromo-VBaseAffPastSmpl-beek"     | "polarity"    | "affirmative"           |
| "oromo-VBaseAffPastSmpl-beek"     | "tam"         | "past"                  |
| "oromo-VBaseMainAffPresSmpl-beek" | "clauseType"  | "main"                  |
| "oromo-VBaseMainAffPresSmpl-beek" | "dervStem"    | "base"                  |
| "oromo-VBaseMainAffPresSmpl-beek" | "polarity"    | "affirmative"           |
| "oromo-VBaseMainAffPresSmpl-beek" | "tam"         | "present"               |
| "oromo-VBaseNegPastSmpl-beek"     | "dervStem"    | "base"                  |
| "oromo-VBaseNegPastSmpl-beek"     | "polarity"    | "negative"              |
| "oromo-VBaseNegPastSmpl-beek"     | "tam"         | "past"                  |
| "oromo-VMidAffPastSmpl-beek"      | "dervStem"    | "T"                     |
| "oromo-VMidAffPastSmpl-beek"      | "polarity"    | "affirmative"           |
| "oromo-VMidAffPastSmpl-beek"      | "tam"         | "past"                  |
| "oromo-VCausAffPastSmpl-beek"     | "dervStem"    | "S"                     |
| "oromo-VCausAffPastSmpl-beek"     | "polarity"    | "affirmative"           |
| "oromo-VCausAffPastSmpl-beek"     | "tam"         | "past"                  |
| "oromo-VCausAffImprtvSmpl-beek"   | "dervStem"    | "S"                     |
| "oromo-VCausAffImprtvSmpl-beek"   | "polarity"    | "affirmative"           |
| "oromo-VCausAffImprtvSmpl-beek"   | "tam"         | "imperative"            |
| "oromo-VMidSubNegPresSmpl-beek"   | "clauseType"  | "subordinate"           |
| "oromo-VMidSubNegPresSmpl-beek"   | "dervStem"    | "T"                     |
| "oromo-VMidSubNegPresSmpl-beek"   | "polarity"    | "negative"              |
| "oromo-VMidSubNegPresSmpl-beek"   | "tam"         | "present"               |
| "oromo-VMidNegImprtvSmpl-beek"    | "dervStem"    | "T"                     |
| "oromo-VMidNegImprtvSmpl-beek"    | "polarity"    | "negative"              |
| "oromo-VMidNegImprtvSmpl-beek"    | "tam"         | "imperative"            |
| "oromo-VMidAffImprtvSmpl-beek"    | "dervStem"    | "T"                     |
| "oromo-VMidAffImprtvSmpl-beek"    | "polarity"    | "affirmative"           |
| "oromo-VMidAffImprtvSmpl-beek"    | "tam"         | "imperative"            |
| "oromo-VBaseMainNegPresSmpl-beek" | "clauseType"  | "main"                  |
| "oromo-VBaseMainNegPresSmpl-beek" | "dervStem"    | "base"                  |
| "oromo-VBaseMainNegPresSmpl-beek" | "polarity"    | "negative"              |
| "oromo-VBaseMainNegPresSmpl-beek" | "tam"         | "present"               |
| "oromo-VCausSubNegPresSmpl-beek"  | "clauseType"  | "subordinate"           |
| "oromo-VCausSubNegPresSmpl-beek"  | "dervStem"    | "S"                     |
| "oromo-VCausSubNegPresSmpl-beek"  | "polarity"    | "negative"              |
| "oromo-VCausSubNegPresSmpl-beek"  | "tam"         | "present"               |
| "oromo-VMidSubAffPresSmpl-beek"   | "clauseType"  | "subordinate"           |
| "oromo-VMidSubAffPresSmpl-beek"   | "dervStem"    | "T"                     |
| "oromo-VMidSubAffPresSmpl-beek"   | "polarity"    | "affirmative"           |
| "oromo-VMidSubAffPresSmpl-beek"   | "tam"         | "present"               |
| "oromo-VCausNegPastSmpl-beek"     | "dervStem"    | "S"                     |
| "oromo-VCausNegPastSmpl-beek"     | "polarity"    | "negative"              |
| "oromo-VCausNegPastSmpl-beek"     | "tam"         | "past"                  |
| "oromo-VCompoundTense"            | "polarity"    | "affirmative"           |
| "oromo-VCompoundTense"            | "polarity"    | "negative"              |
| "oromo-VCompoundTense"            | "tam"         | "conditional"           |
| "oromo-VCompoundTense"            | "tam"         | "futureDefinite"        |
| "oromo-VCompoundTense"            | "tam"         | "futureIndefinite"      |
| "oromo-VCompoundTense"            | "tam"         | "futurePerfect"         |
| "oromo-VCompoundTense"            | "tam"         | "pastProgressive"       |
| "oromo-VCompoundTense"            | "tam"         | "perfect"               |
| "oromo-VCompoundTense"            | "tam"         | "pluperfect"            |
| "oromo-VCompoundTense"            | "tam"         | "pluperfectProgressive" |
| "oromo-VCompoundTense"            | "tam"         | "presentProgressive"    |
| "oromo-VCompoundTense"            | "tokenType"   | "compound"              |
| "oromo-VMidMainNegPresSmpl-beek"  | "clauseType"  | "main"                  |
| "oromo-VMidMainNegPresSmpl-beek"  | "dervStem"    | "T"                     |
| "oromo-VMidMainNegPresSmpl-beek"  | "polarity"    | "negative"              |
| "oromo-VMidMainNegPresSmpl-beek"  | "tam"         | "present"               |
| "oromo-VMidNegPastSmpl-beek"      | "dervStem"    | "T"                     |
| "oromo-VMidNegPastSmpl-beek"      | "polarity"    | "negative"              |
| "oromo-VMidNegPastSmpl-beek"      | "tam"         | "past"                  |
| "oromo-VPassNegImprtvSmpl-beek"   | "dervStem"    | "M"                     |
| "oromo-VPassNegImprtvSmpl-beek"   | "polarity"    | "negative"              |
| "oromo-VPassNegImprtvSmpl-beek"   | "tam"         | "imperative"            |
| "oromo-VMidMainAffPresSmpl-beek"  | "clauseType"  | "main"                  |
| "oromo-VMidMainAffPresSmpl-beek"  | "dervStem"    | "T"                     |
| "oromo-VMidMainAffPresSmpl-beek"  | "polarity"    | "affirmative"           |
| "oromo-VMidMainAffPresSmpl-beek"  | "tam"         | "present"               |
| "oromo-VCausNegImprtvSmpl-beek"   | "dervStem"    | "S"                     |
| "oromo-VCausNegImprtvSmpl-beek"   | "polarity"    | "negative"              |
| "oromo-VCausNegImprtvSmpl-beek"   | "tam"         | "imperative"            |
| "oromo-VPassNegPastSmpl-beek"     | "dervStem"    | "M"                     |
| "oromo-VPassNegPastSmpl-beek"     | "polarity"    | "negative"              |
| "oromo-VPassNegPastSmpl-beek"     | "tam"         | "past"                  |
| "oromo-VJuss-beek"                | "dervStem"    | "M"                     |
| "oromo-VJuss-beek"                | "dervStem"    | "S"                     |
| "oromo-VJuss-beek"                | "dervStem"    | "T"                     |
| "oromo-VJuss-beek"                | "dervStem"    | "base"                  |
| "oromo-VJuss-beek"                | "polarity"    | "affirmative"           |
| "oromo-VJuss-beek"                | "polarity"    | "negative"              |
| "oromo-VJuss-beek"                | "tam"         | "jussive"               |
| "oromo-VPassAffPastSmpl-beek"     | "dervStem"    | "M"                     |
| "oromo-VPassAffPastSmpl-beek"     | "polarity"    | "affirmative"           |
| "oromo-VPassAffPastSmpl-beek"     | "tam"         | "past"                  |
-------------------------------------------------------------------------------
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>

SELECT DISTINCT ?pdgmlabel ?prop1 ?val1 
WHERE 
{
    ?pid ?term aama:pid ;
	aama:pdgmlabel ?pdgmlabel .
	?s ?p ?o ;
    aama:pid ?pid ;
    aama:tam  ?tam ;
	aama:person ?person ;
	aama:lang aama:oromo .
   ?p rdfs:label ?prop1 .
   ?o rdfs:label ?val1  .
  	FILTER (?p NOT IN ( aama:lang, aama:langVar, aama:gender, aama:number, aama:person, aama:pos, rdf:type))
  	FILTER (?o NOT IN ( aama:Term))
 
}
ORDER BY ?pid ?prop1

